{"name": "test_verify_invoice_delete_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.story('Delete created Invoice')\n    def test_verify_invoice_delete_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and delete invoice'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                time.sleep(3)\n                invoice_page.delete_invoice()\n                invoice_page.verify_deletion_message(ValidationTexts.SUCCESSFUL_INVOICE_DELETE)\n                attach_screenshot(page, \"Invoice Deletion Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Deletion Failure\")\n                print(f\"Test 'verify_invoice_delete_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:106: RuntimeError"}, "steps": [{"name": "Login and delete invoice", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 106, in test_verify_invoice_delete_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "c9bd4894-e63b-4aa9-bc08-7016f97807ed-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "82ab6cd5-eb2b-4580-8ebb-2cab811ffe51-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "b6bb6d4a-3711-42d0-a72d-3089d37d8b4e-attachment.txt", "type": "text/plain"}, {"name": "Invoice Deletion Failure", "source": "05d4c54d-14b2-455c-ab4a-1183492e925d-attachment.png", "type": "image/png"}], "start": 1720457833086, "stop": 1720457839960}], "attachments": [{"name": "stdout", "source": "9c38f113-ec55-4c43-8c69-9973d45f3a91-attachment.txt", "type": "text/plain"}], "start": 1720457833004, "stop": 1720457839961, "uuid": "86d92051-89a8-4852-b561-9af64c8f19b4", "historyId": "9060090de2a57dc8e145cf72124402e7", "testCaseId": "9060090de2a57dc8e145cf72124402e7", "fullName": "tests.test_Upload_invoice#test_verify_invoice_delete_status", "labels": [{"name": "story", "value": "Delete created Invoice"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "194284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}