{"name": "test_verify_created_invoice_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.story('Search created Invoice')\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and verify created invoice status'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(invoice_number)\n                time.sleep(3)\n                invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                attach_screenshot(page, \"Invoice Verification Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Verification Failure\")\n                print(f\"Test 'verify_created_invoice_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:76: RuntimeError"}, "steps": [{"name": "Login and verify created invoice status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 76, in test_verify_created_invoice_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "e09e9ee9-52b9-41ff-b140-786dfd405fcc-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "acd115df-bfd1-40d6-ad61-0de0775d64ff-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "1a17bcd1-1e7c-4350-a76c-4af370730198-attachment.txt", "type": "text/plain"}, {"name": "Invoice Verification Failure", "source": "89676b8b-d0ac-41d3-ac6e-ee729d450a50-attachment.png", "type": "image/png"}], "start": 1720457815326, "stop": 1720457827391}], "attachments": [{"name": "stdout", "source": "28445838-c4a6-4612-af80-ad0c27a77ab1-attachment.txt", "type": "text/plain"}], "start": 1720457815229, "stop": 1720457827392, "uuid": "24e5e7d0-c855-40a1-afb0-01fc62c95372", "historyId": "0a6e48d5408d613d4f1eeb54af380e68", "testCaseId": "0a6e48d5408d613d4f1eeb54af380e68", "fullName": "tests.test_Upload_invoice#test_verify_created_invoice_status", "labels": [{"name": "story", "value": "Search created Invoice"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "194284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}