{"name": "test_verify_created_invoice_status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.story('Search created Invoice')\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and verify created invoice status'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(invoice_number)\n                time.sleep(3)\n                invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                attach_screenshot(page, \"Invoice Verification Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Verification Failure\")\n                print(f\"Test 'verify_created_invoice_status' failed: {e}\")\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntests/test_Upload_invoice.py:76: RuntimeError"}, "steps": [{"name": "Login and verify created invoice status", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 76, in test_verify_created_invoice_status\n    raise\n"}, "attachments": [{"name": "Input Username", "source": "46c93e6a-9569-4a16-95f1-6079718f4c6d-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "e65c671f-f920-443e-83a5-ef1f57ed084d-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "886ec9dc-f985-45ed-af89-f9e18c050e6f-attachment.txt", "type": "text/plain"}, {"name": "Invoice Verification Success", "source": "dac34ef6-8fb8-4db1-8b37-eb5584dc77d7-attachment.png", "type": "image/png"}], "start": 1720458107422, "stop": 1720458114209}], "start": 1720458107347, "stop": 1720458114209, "uuid": "4e533d9c-dd51-47e4-8a43-ea707fb6aae9", "historyId": "0a6e48d5408d613d4f1eeb54af380e68", "testCaseId": "0a6e48d5408d613d4f1eeb54af380e68", "fullName": "tests.test_Upload_invoice#test_verify_created_invoice_status", "labels": [{"name": "story", "value": "Search created Invoice"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "196323-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}