{"name": "test_verify_created_invoice_status", "status": "failed", "statusDetails": {"message": "Failed: Failed to verify created invoice status: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_be_visible with timeout 5000ms\n  - waiting for locator(\"//div[contains(@class, 'text-truncate-w100') and contains(text(), 'invoicenumb1')]\")", "trace": "setup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story('Search created Invoice')\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and verify created invoice status'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(invoice_number)\n                time.sleep(3)\n>               invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n\ntests/test_Upload_invoice.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.UploadInvoicePage.UploadInvoicePage object at 0x7f2b4e8744f0>, keyword = 'invoicenumb1'\n\n    def verify_invoice_in_list(self, keyword: str) -> None:\n        try:\n            element = self.page.locator(\n                f\"//div[contains(@class, 'text-truncate-w100') and contains(text(), '{keyword}')]\")\n>           expect(element).to_be_visible()\nE           AssertionError: Locator expected to be visible\nE           Actual value: <element(s) not found> \nE           Call log:\nE           LocatorAssertions.to_be_visible with timeout 5000ms\nE             - waiting for locator(\"//div[contains(@class, 'text-truncate-w100') and contains(text(), 'invoicenumb1')]\")\n\npages/UploadInvoicePage.py:105: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nsetup_and_teardown = <Page url='https://www.tig-test.com/my-frs/frs-invoices'>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story('Search created Invoice')\n    def test_verify_created_invoice_status(setup_and_teardown) -> None:\n        page = setup_and_teardown\n        invoice_page = UploadInvoicePage(page)\n        credentials = {\n            'username': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 1),\n            'password': ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Login\", 2, 2)\n        }\n        invoice_number = ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1)\n    \n        with allure.step('Login and verify created invoice status'):\n            allure.attach(f\"Username: {credentials['username']}\", name=\"Input Username\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Password: {credentials['password']}\", name=\"Input Password\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(f\"Invoice Number: {invoice_number}\", name=\"Invoice Number\",\n                          attachment_type=allure.attachment_type.TEXT)\n            try:\n                invoice_page.login(credentials['username'], credentials['password'])\n                invoice_page.search_invoice(invoice_number)\n                time.sleep(3)\n                invoice_page.verify_invoice_in_list(ExcelUtils.get_cell_data(\"ExcelFiles/Testdata.xlsx\", \"Invoice\", 2, 1))\n                attach_screenshot(page, \"Invoice Verification Success\")\n            except (TimeoutError, Error, AssertionError) as e:\n                attach_screenshot(page, \"Invoice Verification Failure\")\n                print(f\"Test 'verify_created_invoice_status' failed: {e}\")\n>               pytest.fail(f\"Failed to verify created invoice status: {str(e)}\")\nE               Failed: Failed to verify created invoice status: Locator expected to be visible\nE               Actual value: <element(s) not found> \nE               Call log:\nE               LocatorAssertions.to_be_visible with timeout 5000ms\nE                 - waiting for locator(\"//div[contains(@class, 'text-truncate-w100') and contains(text(), 'invoicenumb1')]\")\n\ntests/test_Upload_invoice.py:79: Failed"}, "steps": [{"name": "Login and verify created invoice status", "status": "failed", "statusDetails": {"message": "Failed: Failed to verify created invoice status: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_be_visible with timeout 5000ms\n  - waiting for locator(\"//div[contains(@class, 'text-truncate-w100') and contains(text(), 'invoicenumb1')]\")\n\n", "trace": "  File \"/home/laptop-obs-156/PycharmProjects/Playwright_Walkthrought/tests/test_Upload_invoice.py\", line 79, in test_verify_created_invoice_status\n    pytest.fail(f\"Failed to verify created invoice status: {str(e)}\")\n  File \"/home/laptop-obs-156/miniconda3/lib/python3.9/site-packages/_pytest/outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "Input Username", "source": "22726480-06dd-429b-9f4f-b90576b9ed48-attachment.txt", "type": "text/plain"}, {"name": "Input Password", "source": "70fb918f-546a-42c1-a189-168101827e92-attachment.txt", "type": "text/plain"}, {"name": "Invoice Number", "source": "a7716bf9-ab20-43ad-81fa-ff1bd752972c-attachment.txt", "type": "text/plain"}, {"name": "Invoice Verification Failure", "source": "68659633-9ceb-4105-8dc9-8e0d39b070df-attachment.png", "type": "image/png"}], "start": 1720514823899, "stop": 1720514840205}], "attachments": [{"name": "stdout", "source": "4b2b9a74-6761-4763-a994-d6210ef1a95a-attachment.txt", "type": "text/plain"}], "start": 1720514823829, "stop": 1720514840211, "uuid": "37a9f0ca-e4c2-48d5-9be5-3996068a7dd3", "historyId": "0a6e48d5408d613d4f1eeb54af380e68", "testCaseId": "0a6e48d5408d613d4f1eeb54af380e68", "fullName": "tests.test_Upload_invoice#test_verify_created_invoice_status", "labels": [{"name": "story", "value": "Search created Invoice"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Upload_invoice"}, {"name": "host", "value": "laptop-obs-156"}, {"name": "thread", "value": "57813-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Upload_invoice"}]}